[book]
language = "en"
multilingual = false
src = "docs"
title = "The Standard Documentation"

[build]
build-dir = "docs/book"

[output.html]
additional-js = ["static/mermaid.min.js", "static/mermaid-init.js"]

[preprocessor]
[preprocessor.kroki-preprocessor]
command = "mdbook-kroki-preprocessor"

[preprocessor.mermaid]
command = "mdbook-mermaid"
