name: nix-macos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          skip_adding_nixpkgs_channel: true
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Nix Flake Show
        run: nix flake show

      - name: Build Std
        run: nix run --show-trace --print-build-logs .#x86_64-darwin.std.cli.default -- std --version

      - name: Check std devshells
        run: nix develop --show-trace --print-build-logs .#devShells.x86_64-darwin.checks --command echo OK

      - name: Check std data clade
        run: nix develop --show-trace --print-build-logs .#devShells.x86_64-darwin.checks --command clade-data

      - name: Check default devshell
        run: nix develop --show-trace --print-build-logs .#devShells.x86_64-darwin.default --command echo OK
